
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';  
export const USER_SUCCESS = 'USER_SUCCESS'
export const NEW_USER_SUCCESS = 'NEW_USER_SUCCESS'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'